# -*- coding: utf-8 -*-
HEADERS = {"User-Agent": "Paw/2.2.5 (Macintosh; OS X/10.11.1) GCDHTTPRequest"}
CHANNELS = [
    # {'name': '红心兆赫', 'id': -3},
    {'name': '我的私人兆赫', 'id': 0},
    {'name': '每日私人歌单', 'id': -2},
    {'name': '豆瓣精选兆赫', 'id': -10},
    # 心情 / 场景
    {'name': '工作学习', 'id': 153},
    {'name': '户外', 'id': 151},
    {'name': '休息', 'id': 152},
    {'name': '亢奋', 'id': 154},
    {'name': '舒缓', 'id': 155},
    {'name': 'Easy', 'id': 77},
    {'name': '咖啡', 'id': 32},
    {'name': '运动', 'id': 257},
    # 语言 / 年代
                {'name': '华语', 'id': 1},
    {'name': '欧美', 'id': 2},
    {'name': '七零', 'id': 3},
    {'name': '八零', 'id': 4},
    {'name': '九零', 'id': 5},
    {'name': '粤语', 'id': 6},
    {'name': '日语', 'id': 17},
    {'name': '韩语', 'id': 18},
    {'name': '法语', 'id': 22},
    {'name': '新歌', 'id': 61},
    # 风格 / 流派
                {'name': '流行', 'id': 194},
    {'name': '摇滚', 'id': 7},
    {'name': '民谣', 'id': 8},
    {'name': '轻音乐', 'id': 9},
    {'name': '电影原声', 'id': 10},
    {'name': '爵士', 'id': 13},
    {'name': '电子', 'id': 14},
    {'name': '说唱', 'id': 15},
    {'name': 'R&B', 'id': 16},
    {'name': '古典', 'id': 27},
    {'name': '动漫', 'id': 28},
    {'name': '世界音乐', 'id': 187},
    {'name': '布鲁斯', 'id': 188},
    {'name': '拉丁', 'id': 189},
    {'name': '雷鬼', 'id': 190},
    {'name': '小清新', 'id': 76}
]
